spring.application.name=CinemaBookingOnline

spring.datasource.url=jdbc:postgresql://localhost:5432/cbo
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update